# Generated by Django 3.1 on 2020-08-26 21:14

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique ID for Direction', primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique ID for Student', primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('birthday', models.DateTimeField(default=datetime.datetime(2020, 8, 26, 21, 14, 14, 652793, tzinfo=utc))),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique ID for Subject', primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique ID for University', primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique ID for Score', primary_key=True, serialize=False)),
                ('result', models.IntegerField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adm_lists.student')),
                ('subject', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='adm_lists.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique ID for Program', primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=50)),
                ('places', models.IntegerField()),
                ('spec_places', models.IntegerField()),
                ('target_places', models.IntegerField()),
                ('appl_count', models.IntegerField()),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adm_lists.direction')),
                ('students', models.ManyToManyField(to='adm_lists.Student')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique ID for Faculty', primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=50)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adm_lists.university')),
            ],
        ),
        migrations.AddField(
            model_name='direction',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adm_lists.faculty'),
        ),
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique ID for Admission', primary_key=True, serialize=False)),
                ('level', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('contract', models.CharField(max_length=50)),
                ('contract_type', models.CharField(max_length=50)),
                ('reg_num', models.CharField(max_length=50)),
                ('priority', models.CharField(max_length=50)),
                ('agreement', models.IntegerField()),
                ('total', models.IntegerField()),
                ('exam_sum', models.IntegerField()),
                ('exam_1', models.IntegerField()),
                ('exam_2', models.IntegerField()),
                ('exam_3', models.IntegerField()),
                ('bonus_sum', models.IntegerField()),
                ('bonus_str', models.CharField(max_length=50)),
                ('comment', models.CharField(max_length=50)),
                ('row_id', models.IntegerField()),
                ('scrape_date', models.DateTimeField()),
                ('url', models.CharField(max_length=50)),
                ('updated', models.DateTimeField()),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adm_lists.direction')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adm_lists.faculty')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adm_lists.program')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adm_lists.student')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adm_lists.university')),
            ],
            options={
                'verbose_name': 'admission',
                'verbose_name_plural': 'admissions',
            },
        ),
    ]
