# Generated by Django 3.1 on 2020-08-21 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scrape_date', models.DateTimeField(blank=True, null=True)),
                ('url', models.CharField(blank=True, max_length=50, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('university', models.CharField(blank=True, max_length=50, null=True)),
                ('level', models.CharField(blank=True, max_length=50, null=True)),
                ('faculty', models.CharField(blank=True, max_length=50, null=True)),
                ('direction', models.CharField(blank=True, max_length=50, null=True)),
                ('program', models.CharField(blank=True, max_length=50, null=True)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('contract', models.CharField(blank=True, max_length=50, null=True)),
                ('places', models.IntegerField(blank=True, null=True)),
                ('spec_places', models.IntegerField(blank=True, null=True)),
                ('target_places', models.IntegerField(blank=True, null=True)),
                ('appl_count', models.IntegerField(blank=True, null=True)),
                ('row_id', models.IntegerField(blank=True, null=True)),
                ('reg_num', models.CharField(blank=True, max_length=50, null=True)),
                ('full_name', models.CharField(blank=True, max_length=50, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('contract_type', models.CharField(blank=True, max_length=50, null=True)),
                ('priority', models.CharField(blank=True, max_length=50, null=True)),
                ('total', models.IntegerField(blank=True, null=True)),
                ('exam_sum', models.IntegerField(blank=True, null=True)),
                ('exam_1', models.IntegerField(blank=True, null=True)),
                ('exam_2', models.IntegerField(blank=True, null=True)),
                ('exam_3', models.IntegerField(blank=True, null=True)),
                ('bonus_sum', models.IntegerField(blank=True, null=True)),
                ('agreement', models.IntegerField(blank=True, null=True)),
                ('bonus_str', models.CharField(blank=True, max_length=50, null=True)),
                ('comment', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'admission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(blank=True, max_length=50, null=True)),
                ('average', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('exams', models.ManyToManyField(to='adm_lists.Exam')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('students', models.ManyToManyField(to='adm_lists.Student')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
