# Generated by Django 3.1 on 2020-08-21 15:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('adm_lists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='direction',
            name='d_id',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='direction',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='exam',
            name='average',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='exam',
            name='subject_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='birthday',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 21, 15, 13, 4, 107483, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
